let data = {
  'status': 0,
  'statusInfo': {
    'msg': '查询成功',
    'detail': null
  },
  'data': {
    'node': {
      'id': 'GD01',
      'label': '无线电集团',
      'fullname': '广州无线电集团有限公司',
      'parent_code': '0',
      'children': [{
        'id': 'GD01005',
        'label': '广电研究院',
        'fullname': '广州广电研究院有限公司',
        'parent_code': 'GD01',
        'children': [],
        'tree_level': '1',
        'proportion': 100.0,
        'nature': '全资子公司'
      }, {
        'id': 'GD01006',
        'label': '平云资本',
        'fullname': '广州广电平云资本管理有限公司',
        'parent_code': 'GD01',
        'children': [],
        'tree_level': '1',
        'proportion': 100.0,
        'nature': '全资子公司'
      }, {
        'id': 'GD01007',
        'label': '广电国贸',
        'fullname': '广州广电国际商贸有限公司',
        'parent_code': 'GD01',
        'children': [],
        'tree_level': '1',
        'proportion': 100.0,
        'nature': '全资子公司'
      }, {
        'id': 'GD01008',
        'label': '广电产投',
        'fullname': '广州广电新兴产业园投资有限公司',
        'parent_code': 'GD01',
        'children': [],
        'tree_level': '1',
        'proportion': 100.0,
        'nature': '全资子公司'
      }, {
        'id': 'GD01009',
        'label': '广电智能',
        'fullname': '广州广电智能科技有限公司',
        'parent_code': 'GD01',
        'children': [],
        'tree_level': '1',
        'proportion': 100.0,
        'nature': '全资子公司'
      }, {
        'id': 'GD01002',
        'label': '广电运通',
        'fullname': '广州广电运通金融电子股份有限公司',
        'parent_code': 'GD01',
        'children': [{
          'id': 'GD01002001',
          'label': '广州穗通',
          'fullname': '广州穗通金融服务有限公司',
          'parent_code': 'GD01002',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002002',
          'label': '广州银通',
          'fullname': '广州广电银通金融电子科技有限公司',
          'parent_code': 'GD01002',
          'children': [{
            'id': 'GD01002002001',
            'label': '深圳银通',
            'fullname': '深圳广电银通金融电子科技有限公司',
            'parent_code': 'GD01002002',
            'children': [{
              'id': 'GD01002002001001',
              'label': '上海欣辰通',
              'fullname': '上海欣辰通金融电子科技有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001002',
              'label': '深圳鹏通',
              'fullname': '深圳鹏通金融服务有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001003',
              'label': '河北晨通',
              'fullname': '河北晨通金融电子科技有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001004',
              'label': '辽宁辽通',
              'fullname': '辽宁辽通金融电子科技有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001005',
              'label': '南宁盈通',
              'fullname': '南宁盈通金融电子科技有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001006',
              'label': '宜昌宜通',
              'fullname': '宜昌宜通金融服务有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001007',
              'label': '石家庄银通',
              'fullname': '石家庄市银通金融服务有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001008',
              'label': '河南商通',
              'fullname': '河南商通金融服务外包有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001009',
              'label': '山西尚通',
              'fullname': '山西尚通金融外包服务有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001010',
              'label': '南阳宛通',
              'fullname': '南阳宛通金融电子科技有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002001011',
              'label': '广东榕通',
              'fullname': '广东榕通科技服务有限公司',
              'parent_code': 'GD01002002001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002002002',
            'label': '广电银通安保',
            'fullname': '广州广电银通安保投资有限公司',
            'parent_code': 'GD01002002',
            'children': [{
              'id': 'GD01002002002001',
              'label': '武威神威',
              'fullname': '武威市神威保安有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002002',
              'label': '宜昌金牛',
              'fullname': '宜昌市金牛押运护卫保安服务有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002003',
              'label': '邵阳保安',
              'fullname': '邵阳市保安服务有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [{
                'id': 'GD01002002002003001',
                'label': '南县保安',
                'fullname': '南县保安服务有限责任公司',
                'parent_code': 'GD01002002002003',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }, {
                'id': 'GD01002002002003002',
                'label': '益阳保安',
                'fullname': '益阳市保安服务有限责任公司',
                'parent_code': 'GD01002002002003',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002004',
              'label': '内蒙古安保投资',
              'fullname': '内蒙古广电银通安保投资有限公司',
              'parent_code': 'GD01002002002',
              'children': [{
                'id': 'GD01002002002004001',
                'label': '天力保押',
                'fullname': '巴彦淖尔天力保押有限责任公司',
                'parent_code': 'GD01002002002004',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }, {
                'id': 'GD01002002002004002',
                'label': '威信保安',
                'fullname': '兴安盟威信保安守押服务有限责任公司',
                'parent_code': 'GD01002002002004',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }, {
                'id': 'GD01002002002004003',
                'label': '威远护卫',
                'fullname': '通辽市威远护卫有限责任公司',
                'parent_code': 'GD01002002002004',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002005',
              'label': '鹰翔保安押运',
              'fullname': '平顶山鹰翔保安押运有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002006',
              'label': '蓝盾武装',
              'fullname': '黔南州蓝盾武装护运有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002007',
              'label': '新疆阿帕奇武装',
              'fullname': '新疆阿帕奇武装守护押运有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002008',
              'label': '海南警锐',
              'fullname': '海南警锐押运护卫有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002009',
              'label': '新余保安服务',
              'fullname': '新余市保安服务有限公司',
              'parent_code': 'GD01002002002',
              'children': [{
                'id': 'GD01002002002009001',
                'label': '景运科技',
                'fullname': '新余市景运科技有限公司',
                'parent_code': 'GD01002002002009',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002010',
              'label': '金盾保安守',
              'fullname': '文山州金盾保安守护押运有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002011',
              'label': '西安金盾',
              'fullname': '西安金盾押运有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002012',
              'label': '资阳保安',
              'fullname': '资阳保安有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [{
                'id': 'GD01002002002012001',
                'label': '卓越人力',
                'fullname': '资阳市卓越人力资源服务有限公司',
                'parent_code': 'GD01002002002012',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002013',
              'label': '商洛金盾',
              'fullname': '商洛市金盾押运有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [{
                'id': 'GD01002002002013001',
                'label': '慧金清分',
                'fullname': '商洛市慧金清分服务有限公司',
                'parent_code': 'GD01002002002013',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002014',
              'label': '黄石金通',
              'fullname': '黄石金通智慧金融外包服务有限公司',
              'parent_code': 'GD01002002002',
              'children': [{
                'id': 'GD01002002002014001',
                'label': '金安押运',
                'fullname': '黄石市金安押运护卫保安服务有限公司',
                'parent_code': 'GD01002002002014',
                'children': [],
                'tree_level': '5',
                'proportion': 62.1,
                'nature': '控股公司'
              }],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002015',
              'label': '保山安邦',
              'fullname': '保山安邦武装守护押运有限责任公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002016',
              'label': '湖北银通',
              'fullname': '湖北银通卓越科技服务有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002017',
              'label': '巴州阿帕奇',
              'fullname': '巴州阿帕奇保安责任有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002018',
              'label': '鹤壁鹏翔',
              'fullname': '鹤壁市鹏翔保安服务有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002002002019',
              'label': '湖北融信',
              'fullname': '湖北融信押运保安服务有限公司',
              'parent_code': 'GD01002002002',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002002003',
            'label': '平云小匠',
            'fullname': '广州平云小匠科技有限公司',
            'parent_code': 'GD01002002',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002002004',
            'label': '信义科技',
            'fullname': '深圳市信义科技有限公司',
            'parent_code': 'GD01002002',
            'children': [{
              'id': 'GD01002002004001',
              'label': '深安信信息',
              'fullname': '深圳市深安信信息技术有限公司',
              'parent_code': 'GD01002002004',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002003',
          'label': '龙源环保',
          'fullname': '广州市龙源环保科技有限公司',
          'parent_code': 'GD01002',
          'children': [{
            'id': 'GD01002003001',
            'label': '赣州中联',
            'fullname': '赣州中联环保科技开发有限公司',
            'parent_code': 'GD01002003',
            'children': [{
              'id': 'GD01002003001001',
              'label': '赣州龙源环保',
              'fullname': '赣州龙源环保产业经营管理有限公司',
              'parent_code': 'GD01002003001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }, {
              'id': 'GD01002003001002',
              'label': '赣州中联电镀',
              'fullname': '赣州中联电镀原料配送经营服务有限公司',
              'parent_code': 'GD01002003001',
              'children': [],
              'tree_level': '4',
              'proportion': 62.1,
              'nature': '控股公司'
            }],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002004',
          'label': '运通国际',
          'fullname': '广电运通国际有限公司',
          'parent_code': 'GD01002',
          'children': [{
            'id': 'GD01002004001',
            'label': 'GRGTBE',
            'fullname': 'GRG Turkiye Bankacilik Ekipmanlari',
            'parent_code': 'GD01002004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002004002',
            'label': 'GATMCo.L',
            'fullname': 'Global ATM Parts Co.,Litmited',
            'parent_code': 'GD01002004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002004003',
            'label': 'GRG HK',
            'fullname': 'GRG Hongkong Mexico,S.A.DE',
            'parent_code': 'GD01002004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002004004',
            'label': '立陶宛公司',
            'fullname': '立陶宛公司',
            'parent_code': 'GD01002004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002004005',
            'label': 'GRG DG',
            'fullname': 'GRG Deutschland GmgH（德国）',
            'parent_code': 'GD01002004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002004006',
            'label': 'GRG EP.Ltd',
            'fullname': 'GRG Equipment (Singapore) Pte.Ltd.（新加坡）',
            'parent_code': 'GD01002004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002004007',
            'label': '运通国贸',
            'fullname': '广电运通国际商贸（广州）有限公司',
            'parent_code': 'GD01002004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002005',
          'label': '运通信息',
          'fullname': '广州广电运通信息科技有限公司',
          'parent_code': 'GD01002',
          'children': [{
            'id': 'GD01002005001',
            'label': '运通卓识',
            'fullname': '广州广电卓识智能科技有限公司',
            'parent_code': 'GD01002005',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002006',
          'label': '支点创业',
          'fullname': '广州支点创业投资有限公司',
          'parent_code': 'GD01002',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002007',
          'label': '中智融通',
          'fullname': '广州中智融通金融科技有限公司',
          'parent_code': 'GD01002',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002008',
          'label': '深圳创自',
          'fullname': '深圳市创自技术有限公司',
          'parent_code': 'GD01002',
          'children': [{
            'id': 'GD01002008001',
            'label': '创自软件',
            'fullname': '深圳市创自软件有限公司',
            'parent_code': 'GD01002008',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002009',
          'label': '运通智能',
          'fullname': '广州广电运通智能科技有限公司',
          'parent_code': 'GD01002',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002010',
          'label': '汇通金融',
          'fullname': '广州广电汇通金融服务有限公司',
          'parent_code': 'GD01002',
          'children': [{
            'id': 'GD01002010001',
            'label': '广电汇通(香港)',
            'fullname': '广电汇通(香港)有限公司',
            'parent_code': 'GD01002010',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002011',
          'label': '江苏汇通',
          'fullname': '江苏汇通金融数据股份有限公司',
          'parent_code': 'GD01002',
          'children': [{
            'id': 'GD01002011001',
            'label': '安徽汇通',
            'fullname': '安徽汇通金融数据服务有限公司',
            'parent_code': 'GD01002011',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01002011002',
            'label': '江苏汇锦',
            'fullname': '江苏汇锦利通信息科技有限公司',
            'parent_code': 'GD01002011',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01002012',
          'label': '运通科技',
          'fullname': '北京广电运通科技有限公司',
          'parent_code': 'GD01002',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }],
        'tree_level': '1',
        'proportion': 62.1,
        'nature': '控股公司'
      }, {
        'id': 'GD01003',
        'label': '广电物业',
        'fullname': '广州广电物业管理有限公司',
        'parent_code': 'GD01',
        'children': [{
          'id': 'GD01003001',
          'label': '长沙粤电物业',
          'fullname': '长沙粤电物业管理有限公司',
          'parent_code': 'GD01003',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01003002',
          'label': '鑫广电物业',
          'fullname': '广州鑫广电物业服务有限公司',
          'parent_code': 'GD01003',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01003003',
          'label': '广电保安',
          'fullname': '广东广电保安服务有限公司',
          'parent_code': 'GD01003',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01003004',
          'label': '佛山广电资产',
          'fullname': '佛山广电资产管理有限公司',
          'parent_code': 'GD01003',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01003005',
          'label': '广电羽毛球',
          'fullname': '广州广电羽毛球产业有限公司',
          'parent_code': 'GD01003',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01003006',
          'label': '福建粤电物业',
          'fullname': '福建粤电城市物业服务有限公司',
          'parent_code': 'GD01003',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }],
        'tree_level': '1',
        'proportion': 62.1,
        'nature': '控股公司'
      }, {
        'id': 'GD01004',
        'label': '广电计量',
        'fullname': '广州广电计量检测股份有限公司',
        'parent_code': 'GD01',
        'children': [{
          'id': 'GD01004011',
          'label': '广州九顶软件',
          'fullname': '广州九顶软件股份有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 100.0,
          'nature': '全资子公司'
        }, {
          'id': 'GD01004012',
          'label': '广电计量（南宁）',
          'fullname': '广电计量检测（南宁）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 100.0,
          'nature': '全资子公司'
        }, {
          'id': 'GD01004013',
          'label': '广电计量（福州）',
          'fullname': '广电计量检测（福州）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 100.0,
          'nature': '全资子公司'
        }, {
          'id': 'GD01004014',
          'label': '广电计量（上海）',
          'fullname': '广电计量检测（上海）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 100.0,
          'nature': '全资子公司'
        }, {
          'id': 'GD01004015',
          'label': '广电计量（重庆）',
          'fullname': '广电计量检测（重庆）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 100.0,
          'nature': '全资子公司'
        }, {
          'id': 'GD01004016',
          'label': '广电计量（青岛）',
          'fullname': '广电计量检测（青岛）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 100.0,
          'nature': '全资子公司'
        }, {
          'id': 'GD01004001',
          'label': '广电计量（湖南）',
          'fullname': '广电计量检测（湖南）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004002',
          'label': '广电计量（无锡）',
          'fullname': '广州广电计量检测无锡有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004003',
          'label': '广电计量（西安）',
          'fullname': '广电计量检测（西安）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004004',
          'label': '广电计量（成都）',
          'fullname': '广电计量检测（成都）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004005',
          'label': '广电计量（北京）',
          'fullname': '广电计量检测（北京）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004006',
          'label': '广电计量（天津）',
          'fullname': '广电计量检测（天津）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004007',
          'label': '广电计量（河南）',
          'fullname': '河南广电计量检测有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004008',
          'label': '山锋测控',
          'fullname': '广州山锋测控技术有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004009',
          'label': '广电计量（武汉）',
          'fullname': '广电计量检测（武汉）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01004010',
          'label': '广电计量（沈阳）',
          'fullname': '广电计量检测（沈阳）有限公司',
          'parent_code': 'GD01004',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }],
        'tree_level': '1',
        'proportion': 62.1,
        'nature': '控股公司'
      }, {
        'id': 'GD01001',
        'label': '海格通信',
        'fullname': '广州海格通信集团股份有限公司',
        'parent_code': 'GD01',
        'children': [{
          'id': 'GD01001003',
          'label': '嵘兴实业',
          'fullname': '深圳市嵘兴实业发展有限公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001003001',
            'label': '山东嵘兴通信',
            'fullname': '山东嵘兴通信技术有限公司',
            'parent_code': 'GD01001003',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001004',
          'label': '南方海岸',
          'fullname': '广东南方海岸科技服务有限公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001004001',
            'label': '裕联科技',
            'fullname': '裕联科技发展有限公司',
            'parent_code': 'GD01001004',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001005',
          'label': '海华电子',
          'fullname': '海华电子企业（中国）有限公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001005001',
            'label': '海华电子（香港）',
            'fullname': '海华电子企业（香港）有限公司',
            'parent_code': 'GD01001005',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01001005002',
            'label': '海华交通科技',
            'fullname': '广州海华交通科技有限公司',
            'parent_code': 'GD01001005',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01001005003',
            'label': '海格亚华',
            'fullname': '广州海格亚华防务科技有限公司',
            'parent_code': 'GD01001005',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001006',
          'label': '长沙海格',
          'fullname': '长沙海格北斗信息技术有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001007',
          'label': '北京海格',
          'fullname': '北京海格云熙技术有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001008',
          'label': '通导信息',
          'fullname': '广州通导信息技术服务有限公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001008001',
            'label': '深圳康来士',
            'fullname': '深圳康来士标准测试技术有限公司',
            'parent_code': 'GD01001008',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001009',
          'label': '陕西海通',
          'fullname': '陕西海通天线有限责任公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001009001',
            'label': '海云天线',
            'fullname': '陕西海云天线有限责任公司',
            'parent_code': 'GD01001009',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001010',
          'label': '海格神舟',
          'fullname': '北京海格神舟通信科技有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001011',
          'label': '广州润芯',
          'fullname': '广州润芯信息技术有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001012',
          'label': '海格恒通',
          'fullname': '四川海格恒通专网科技有限公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001012001',
            'label': '承联通信',
            'fullname': '杭州承联通信技术有限公司',
            'parent_code': 'GD01001012',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001013',
          'label': '北京爱尔达',
          'fullname': '北京爱尔达电子设备有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001014',
          'label': '海格资产',
          'fullname': '北京海格资产管理有限公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001014001',
            'label': '海格天腾',
            'fullname': '广州海格天腾传媒有限公司',
            'parent_code': 'GD01001014',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001015',
          'label': '广州寰坤',
          'fullname': '广州寰坤通信科技发展有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001016',
          'label': '海格星航',
          'fullname': '广州海格星航信息科技有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001017',
          'label': '广州福康泉',
          'fullname': '广州福康泉药业有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001018',
          'label': '西安驰达',
          'fullname': '西安驰达飞机零部件制造股份有限公司',
          'parent_code': 'GD01001',
          'children': [{
            'id': 'GD01001018001',
            'label': '西安优盛航空',
            'fullname': '西安优盛航空科技有限公司',
            'parent_code': 'GD01001018',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01001018002',
            'label': '西安厦鹭刀具',
            'fullname': '西安厦鹭刀具有限公司',
            'parent_code': 'GD01001018',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }, {
            'id': 'GD01001018003',
            'label': '宝尔捷（西安）',
            'fullname': '宝尔捷（西安）自动化设备有限公司',
            'parent_code': 'GD01001018',
            'children': [],
            'tree_level': '3',
            'proportion': 62.1,
            'nature': '控股公司'
          }],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }, {
          'id': 'GD01001019',
          'label': '武汉嘉瑞',
          'fullname': '武汉嘉瑞科技有限公司',
          'parent_code': 'GD01001',
          'children': [],
          'tree_level': '2',
          'proportion': 62.1,
          'nature': '控股公司'
        }],
        'tree_level': '1',
        'proportion': 54.11,
        'nature': '控股公司'
      }],
      'tree_level': '0',
      'proportion': 100.0,
      'nature': ''
    },
    'whollyOwned': 11,
    'holding': 120
  }
}
export default data.data.node
